version: "3.7"
services:
    db:
        image: mongo
        container_name: school-management-db
        ports:
            - ${DB_PORT}:${DB_PORT}
        networks:
            - rede
    node:
        build: .
        container_name: school-management-node
        environment:
            - DB_URI=${DB_URI}
            - BACK_PORT=${BACK_PORT}
        expose:
            - ${BACK_PORT}
        volumes:
            - "./:/usr/src/app"
            - /usr/src/app/node_modules
        ports:
            - ${BACK_PORT}:${BACK_PORT}
        depends_on:
            - db
        networks:
            - rede
networks:
    rede:
        driver: bridge
