version: "3.7"
services:
    product-management:
        build: .
        container_name: product-management-node
        environment:
            - BACK_PORT=${BACK_PORT}
        expose:
            - ${BACK_PORT}
        volumes:
            - "./:/usr/src/app"
            - /usr/src/app/node_modules
        ports:
            - ${BACK_PORT}:${BACK_PORT}
        networks:
            - rede
networks:
    rede:
        driver: bridge
